{
    "name": "Hospital Management",
    'summary': "Hospital Management.",
    'description': """Hospital Management""",
    'author': "Deepak Verma",
    'website': "",
    'maintainer': 'Deepak Verma',
    'support': 'Deepak Verma',
    'version': '1.0.0',
    'depends': ['base', 'website', 'mail'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'wizard/appointment_request_wizard.xml',
        'reports/patient_appointment_report.xml',
        'data/appointment_sequence.xml',
        'views/patient_form_template.xml',
        'views/hospital_patient.xml',
        'views/hospital_appointment.xml',
        'views/hospital_doctor.xml',
        'views/rejection_reason.xml',
    ],
    'demo': [],
    'qweb': [],
    'sequence': '1',
    'installable': True,
    'application': True,
    'auto_install': False,
}