{
    'name': 'School Management',
    'version': '1.0',
    'category': 'management',
    'summary': 'School Management',
    'description': 'This app helps to manage the student data management',
    'sequence': '1',
    'author': 'Deepak Verma',
    'maintainer': 'Deepak Verma',
    'website': 'deepakverma.com',
    'depends': ['base'],
    'demo': [],
    'data': ['wizard/student_class_wizard.xml',
             'security/ir.model.access.csv',
             'views/assets.xml',
             'reports/patient_appointment_report.xml',
             'reports/student_card.xml',
             'views/school_division.xml',
             'views/school_subject.xml',
             'views/school_class.xml',
             'views/school_subject_class.xml',
             'views/school_student_subject.xml',
             'views/school_year.xml',
             'views/school_exams.xml',
             'views/school_student.xml',
             'views/school_student_class.xml',
             'views/school_student_exam.xml',
             'views/toggle_button.xml',],
    'installble': True,
    'application': True,
    'auto_install': False,
}
